/** Datos de ejemplo (MODO DEMO) — espejan los mockups y el seed.sql.
 *  Se usan solo cuando Supabase no está configurado. */

const hoursAgo = (h) => new Date(Date.now() - h * 3600_000).toISOString()
const daysAgo = (d) => new Date(Date.now() - d * 86_400_000).toISOString()

export const MOCK_PROFILE = {
  id: 'demo-user',
  full_name: 'Marcos Neifert',
  role: 'Gerente de Ventas',
  avatar_url: 'https://i.pravatar.cc/120?img=12',
}

const RAW_VEHICLES = [
  {
    id: 'v1',
    brand: 'Audi',
    model: 'RS e-tron GT',
    year: 2024,
    price_usd: 185000,
    km: 0,
    fuel_type: 'Eléctrico',
    transmission: 'Automática',
    engine: 'Dual Motor',
    category: 'electrico',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1610768764270-790fbec18178?auto=format&fit=crop&w=800&q=80',
    description: 'Gran turismo eléctrico de alto rendimiento. 0 km, listo para entrega.',
  },
  {
    id: 'v2',
    brand: 'Porsche',
    model: '911 Carrera S',
    year: 2023,
    price_usd: 245000,
    km: 1200,
    fuel_type: 'Nafta',
    transmission: 'PDK',
    engine: '3.0L Flat-6',
    category: 'sport',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    description: 'Ícono deportivo con caja PDK. Estado impecable.',
  },
  {
    id: 'v3',
    brand: 'BMW',
    model: 'X5 M Competition',
    year: 2024,
    price_usd: 165000,
    km: 0,
    fuel_type: 'Nafta',
    transmission: 'M Steptronic',
    engine: '4.4L V8 Biturbo',
    category: 'suv',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80',
    description: 'SUV de altas prestaciones. Unidad 0 km.',
  },
  {
    id: 'v4',
    brand: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2022,
    price_usd: 310000,
    km: 5400,
    fuel_type: 'Nafta',
    transmission: 'AMG Speedshift',
    engine: '4.0L V8 Biturbo',
    category: 'suv',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&w=800&q=80',
    description: 'El SUV de lujo más deseado. Excelente estado.',
  },
  {
    id: 'v5',
    brand: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2024,
    price_usd: 198000,
    km: 0,
    fuel_type: 'Híbrido',
    transmission: 'Automática',
    engine: '3.0L i6 MHEV',
    category: 'suv',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=800&q=80',
    description: 'Lujo británico híbrido. Unidad nueva.',
  },
  {
    id: 'v6',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2023,
    price_usd: 420000,
    km: 800,
    fuel_type: 'Nafta',
    transmission: 'F1 Dual-Clutch',
    engine: '3.9L V8 Turbo',
    category: 'coupe',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=800&q=80',
    description: 'La Nuova Dolce Vita. Estado de colección.',
  },
  {
    id: 'v7',
    brand: 'Maserati',
    model: 'Grecale Trofeo',
    year: 2024,
    price_usd: 145000,
    km: 0,
    fuel_type: 'Nafta',
    transmission: 'Automática',
    engine: '3.0L V6 Nettuno',
    category: 'suv',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=800&q=80',
    description: 'SUV italiano con motor Nettuno. 0 km.',
  },
  {
    id: 'v8',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2023,
    price_usd: 115000,
    km: 2100,
    fuel_type: 'Eléctrico',
    transmission: 'Automática',
    engine: 'Tri Motor',
    category: 'electrico',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80',
    description: 'Berlina eléctrica de máxima performance.',
  },
  {
    id: 'v9',
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2024,
    price_usd: 145000,
    km: 0,
    fuel_type: 'Nafta',
    transmission: 'M Steptronic',
    engine: '3.0L Twin-Turbo',
    category: 'coupe',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80',
    description: 'Coupé deportivo 0 km. Disponible para entrega inmediata.',
  },
  {
    id: 'v10',
    brand: 'Audi',
    model: 'RS6 Avant Performance',
    year: 2023,
    price_usd: 178000,
    km: 3200,
    fuel_type: 'Nafta',
    transmission: 'Tiptronic',
    engine: '4.0L V8 TFSI',
    category: 'sport',
    is_new: true,
    status: 'disponible',
    main_image_url:
      'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=800&q=80',
    description: 'La familiar más rápida. Performance pack.',
  },
]

/** Tomas extra (detalle/interior) para simular varias fotos por vehículo:
 *  habilita el cambio de imagen al hover y el carrusel en el detalle. */
const EXTRA_SHOTS = [
  'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=800&q=80',
]

export const MOCK_VEHICLES = RAW_VEHICLES.map((v, i) => ({
  ...v,
  images: [
    v.main_image_url,
    EXTRA_SHOTS[i % EXTRA_SHOTS.length],
    EXTRA_SHOTS[(i + 2) % EXTRA_SHOTS.length],
  ],
}))

export const MOCK_STORIES = [
  {
    id: 's1',
    kind: 'video',
    title: 'El Arte de la Conducción',
    caption: 'Entrega a Mariana de su Porsche',
    duration: '0:45',
    poster_url:
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=900&q=80',
    video_url: null,
    order_index: 1,
  },
  {
    id: 't1',
    kind: 'testimonial',
    quote: 'El trato fue impecable y encontré exactamente el auto que soñaba.',
    author_name: 'Mariana López',
    author_role: 'Compradora',
    order_index: 2,
  },
  {
    id: 's2',
    kind: 'video',
    title: 'Ingeniería de Precisión',
    caption: 'Entrega a Javier de su Audi',
    duration: '1:20',
    poster_url:
      'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=900&q=80',
    video_url: null,
    order_index: 3,
  },
  {
    id: 't2',
    kind: 'testimonial',
    quote: 'Servicio profesional y entrega puntual; superaron mis expectativas.',
    author_name: 'Javier Morales',
    author_role: 'Empresario',
    order_index: 4,
  },
  {
    id: 't3',
    kind: 'testimonial',
    quote: 'Calidad y atención al detalle en cada paso del proceso.',
    author_name: 'Ana Ruiz',
    author_role: 'Arquitecta',
    order_index: 5,
  },
  {
    id: 's3',
    kind: 'video',
    title: 'Experiencia Electrificada',
    caption: 'Entrega a Diego de su Audi e-tron',
    duration: '2:15',
    poster_url:
      'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=900&q=80',
    video_url: null,
    order_index: 6,
  },
  {
    id: 't4',
    kind: 'testimonial',
    quote: 'Recomiendo Neifert por su asesoramiento personalizado.',
    author_name: 'Diego Fernández',
    author_role: 'Ingeniero',
    order_index: 7,
  },
]

export const MOCK_LEADS = [
  {
    id: 'l1',
    full_name: 'Roberto Sánchez',
    phone: '+54 9 11 2345 6789',
    email: 'roberto.sanchez@email.com',
    vehicle_interest: 'BMW M3 Competition',
    source: 'Instagram',
    status: 'nuevo',
    notes: 'Consultó por financiación.',
    last_contact_at: hoursAgo(1),
    created_at: hoursAgo(1),
    avatar_url: 'https://i.pravatar.cc/80?img=33',
  },
  {
    id: 'l2',
    full_name: 'María Eugenia Ferreyra',
    phone: '+54 9 11 3456 7890',
    email: 'm.ferreyra@email.com',
    vehicle_interest: 'Porsche Macan S',
    source: 'Web',
    status: 'seguimiento',
    notes: 'Pidió test drive para el sábado.',
    last_contact_at: hoursAgo(2),
    created_at: hoursAgo(26),
    avatar_url: 'https://i.pravatar.cc/80?img=45',
  },
  {
    id: 'l3',
    full_name: 'Lucas Giardinelli',
    phone: '+54 9 11 4567 8901',
    email: 'lucas.g@email.com',
    vehicle_interest: 'Audi Q5 Quattro',
    source: 'Showroom',
    status: 'seguimiento',
    notes: 'Interesado en permuta.',
    last_contact_at: daysAgo(1),
    created_at: daysAgo(2),
    avatar_url: 'https://i.pravatar.cc/80?img=51',
  },
  {
    id: 'l4',
    full_name: 'Sofía Martínez',
    phone: '+54 9 11 5678 9012',
    email: 'sofia.m@email.com',
    vehicle_interest: 'Mercedes-Benz C300',
    source: 'Referido',
    status: 'cerrado',
    notes: 'Operación cerrada. Entrega coordinada.',
    last_contact_at: daysAgo(1),
    created_at: daysAgo(5),
    avatar_url: 'https://i.pravatar.cc/80?img=20',
  },
  {
    id: 'l5',
    full_name: 'Alejandro Rossi',
    phone: '+54 9 11 6789 0123',
    email: 'a.rossi@email.com',
    vehicle_interest: 'Audi RS6 Avant Performance',
    source: 'WhatsApp',
    status: 'nuevo',
    notes: 'Pendiente de cita.',
    last_contact_at: hoursAgo(0.16),
    created_at: hoursAgo(0.16),
    avatar_url: 'https://i.pravatar.cc/80?img=13',
  },
  {
    id: 'l6',
    full_name: 'Martina Valenzuela',
    phone: '+54 9 11 7890 1234',
    email: 'martina.v@email.com',
    vehicle_interest: 'Porsche 911 GT3 RS',
    source: 'Instagram',
    status: 'vip',
    notes: 'Cliente VIP. Calificada.',
    last_contact_at: hoursAgo(0.75),
    created_at: daysAgo(1),
    avatar_url: 'https://i.pravatar.cc/80?img=47',
  },
  {
    id: 'l7',
    full_name: 'Roberto Gómez',
    phone: '+54 9 11 8901 2345',
    email: 'r.gomez@email.com',
    vehicle_interest: 'Mercedes-Benz G63 AMG',
    source: 'Showroom',
    status: 'negociacion',
    notes: 'En negociación de precio.',
    last_contact_at: hoursAgo(2),
    created_at: daysAgo(3),
    avatar_url: 'https://i.pravatar.cc/80?img=53',
  },
  {
    id: 'l8',
    full_name: 'Sofía Méndez',
    phone: '+54 9 11 9012 3456',
    email: 'sofia.mendez@email.com',
    vehicle_interest: 'Ferrari 296 GTB',
    source: 'Web',
    status: 'primer_contacto',
    notes: 'Primer contacto vía formulario web.',
    last_contact_at: hoursAgo(3),
    created_at: hoursAgo(3),
    avatar_url: 'https://i.pravatar.cc/80?img=44',
  },
]

export const MOCK_STATS = {
  kpis: {
    ventasTotales: { value: 142, delta: 12.5 },
    nuevosLeads: { value: 1284, delta: 8.2 },
    visitasWeb: { value: 45200, delta: -2.1 },
    tasaConversion: { value: 3.4, delta: 0.8 },
  },
  weeklyTraffic: [
    { day: 'Mar', web: 320, showroom: 90 },
    { day: 'Mié', web: 280, showroom: 410 },
    { day: 'Jue', web: 300, showroom: 250 },
    { day: 'Vie', web: 360, showroom: 300 },
    { day: 'Sáb', web: 420, showroom: 360 },
    { day: 'Dom', web: 250, showroom: 180 },
  ],
  leadsByChannel: [
    { channel: 'WhatsApp', value: 45 },
    { channel: 'Web', value: 30 },
    { channel: 'Instagram', value: 14 },
    { channel: 'Referidos', value: 9 },
  ],
  topModels: [
    { rank: 1, name: 'BMW M4 Competition', sub: 'Coupé 2024', interest: 84, sold: 12, delta: 15 },
    { rank: 2, name: 'Audi RS6 Avant', sub: 'Performance 2023', interest: 76, sold: 8, delta: 5 },
    { rank: 3, name: 'Porsche 911 GT3', sub: '992 Edition', interest: 72, sold: 7, delta: -2 },
  ],
  closingTrend: [
    { day: 'L', value: 18 },
    { day: 'M', value: 20 },
    { day: 'M', value: 19 },
    { day: 'J', value: 22 },
    { day: 'V', value: 21 },
    { day: 'S', value: 24 },
    { day: 'D', value: 24 },
  ],
  closingRate: { value: 24, delta: 4.2 },
}
